apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::793916195974:role/test-eks-LTffbSZn20190625111140229500000006
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::66666666666:role/role1
      username: role1
      groups:
        - system:masters

  mapUsers: |
    - userarn: arn:aws:iam::66666666666:user/user1
      username: user1
      groups:
        - system:masters
    - userarn: arn:aws:iam::66666666666:user/user2
      username: user2
      groups:
        - system:masters

  mapAccounts: |
    - "777777777777"
    - "888888888888"

